name: empowerhr_moblie
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.3.4
  equatable: ^2.0.7
  intl: ^0.18.1
  fl_chart: ^0.68.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  web_socket_channel: ^3.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env.dev
    - assets/background.png
    - assets/LOGO-02.png
    - assets/forgotPasswordImg.png
    - assets/verifyImg.png
    - assets/change_new_password_IMG.png
    - assets/image.png
    - assets/QR_code.png
    - assets/icons/home_icon1.png
    - assets/icons/home_icon2.png
    - assets/icons/chat_icon1.png
    - assets/icons/chat_icon2.png
    - assets/icons/project_icon1.png
    - assets/icons/project_icon2.png
    - assets/icons/report_icon1.png
    - assets/icons/report_icon2.png
    - assets/icons/account_icon1.png
    - assets/icons/account_icon2.png
    - assets/icons/bell.png
    - assets/icons/building-library.png
    - assets/icons/check-badge.png
    - assets/icons/finger-print.png
    - assets/icons/hand-raised.png
    - assets/icons/lock-closed.png
    - assets/icons/moon.png
    - assets/icons/shield-check.png
    - assets/icons/arrow-small-right.png
    - assets/icons/user-circle.png
    - assets/error1.png
    - assets/error2.png
    - assets/qr-code.png
    - assets/thongbao.png
    - assets/calendar-days.png
    - assets/HomepageQR.png
    - assets/HomepageQR(1).png
    - assets/HomepageQR(2).png
    - assets/HomepageQR(3).png
    - assets/checkSuccess.png
    - assets/CombinedShape.png
    - assets/background_account.png
    - assets/chevron-left.png
    - assets/edit_info.png
    - assets/headerWorklog.png
    - assets/bacgroundPopup.png
    - assets/camera.png
    - assets/photo.png
    - assets/absence_form_bg.png
    - assets/create_request_bg.png
    - assets/overtime_bg.png
    - assets/calendar-day.png
    - assets/calendar-daysColor.png
    - assets/backgroundMess.png
    - assets/backgroundetailMess.png
    - assets/header_calender/header_1.png
    - assets/header_calender/header_2.png
    - assets/header_calender/header_3.png
    - assets/header_calender/header_4.png
    - assets/header_calender/header_5.png
    - assets/header_calender/header_6.png
    - assets/header_calender/header_7.png
    - assets/header_calender/header_8.png
    - assets/header_calender/header_9.png
    - assets/header_calender/header_10.png
    - assets/header_calender/header_11.png
    - assets/header_calender/header_12.png
    - assets/background_notification.png

