name: empowerhr_moblie
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.3.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env.dev
    - .env.prod
    - assets/background.png
    - assets/LOGO-02.png
